function Hd = filterDesign2
%FILTERDESIGN2 Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 9.5 and DSP System Toolbox 9.7.
% Generated on: 06-Dec-2022 00:02:07

% FIR least-squares Lowpass filter designed using the FIRLS function.

% All frequency values are in Hz.
Fs = 100000000;  % Sampling Frequency

N     = 511;     % Order
Fpass = 20000;   % Passband Frequency
Fstop = 700000;  % Stopband Frequency
Wpass = 1;       % Passband Weight
Wstop = 10;      % Stopband Weight

% Calculate the coefficients using the FIRLS function.
b  = firls(N, [0 Fpass Fstop Fs/2]/(Fs/2), [1 1 0 0], [Wpass Wstop]);
Hd = dfilt.dffir(b);

% [EOF]
