webtalk_init -webtalk_dir /home/soganli/git_workspace/Tbtk/dataProcessor/dataProcessor.sim/sim_1/behav/xsim/xsim.dir/dataProcessor_tb_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Wed Dec  7 02:09:32 2022" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2020.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "3064766" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "LIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "3ad639ac-a745-40c0-ad13-a8cda8cc71ac" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "fc46981a62ae4671b821c9ca1f102e2d" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "19" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Ubuntu" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Ubuntu 18.04.6 LTS" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "3876.487 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "16.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key runall -value "true" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key runall -value "true" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key runall -value "true" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key runall -value "true" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key runall -value "true" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key runall -value "true" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key runall -value "true" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "1239785 ns" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "27" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "1386.74_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "234352_KB" -context "xsim\\usage"
webtalk_transmit -clientid 1062834233 -regid "" -xml /home/soganli/git_workspace/Tbtk/dataProcessor/dataProcessor.sim/sim_1/behav/xsim/xsim.dir/dataProcessor_tb_behav/webtalk/usage_statistics_ext_xsim.xml -html /home/soganli/git_workspace/Tbtk/dataProcessor/dataProcessor.sim/sim_1/behav/xsim/xsim.dir/dataProcessor_tb_behav/webtalk/usage_statistics_ext_xsim.html -wdm /home/soganli/git_workspace/Tbtk/dataProcessor/dataProcessor.sim/sim_1/behav/xsim/xsim.dir/dataProcessor_tb_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
